# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qi59JHbIczNifcl8rL7kLxEdDVfiwNcr
"""

import pandas as pd
from datetime import datetime

df = pd.read_csv('perishable_inventory.csv')


df['Arrival_Date'] = pd.to_datetime(df['Arrival_Date'])
df['Expiry_Date'] = pd.to_datetime(df['Expiry_Date'])

today = pd.to_datetime('2025-06-30')  # or use datetime.today()
df['Days_Left'] = (df['Expiry_Date'] - today).dt.days
df['Sell_Out_Days'] = df['Quantity'] / df['Daily_Sales']

def get_risk(row):
    if row['Days_Left'] <= 0:
        return 'Expired'
    elif row['Sell_Out_Days'] > row['Days_Left']:
        return 'High'
    elif row['Sell_Out_Days'] <= row['Days_Left']:
        return 'Low'
    else:
        return 'Medium'

df['Spoilage_Risk'] = df.apply(get_risk, axis=1)

print(df[['Product_Name', 'Days_Left', 'Sell_Out_Days', 'Spoilage_Risk']])

